version: '3'
services:
    laravelapi:
        build:
          context: .
          args:
            - UID=${DOCKER_UID}
            - GID=${DOCKER_GID}
        user: ${DOCKER_UID}
        volumes:
            - laravelapi-app-sync:/var/www
            - laravelapi-vendor-sync:/var/www/vendor
        depends_on:
            - laravelapi-postgres
            - laravelapi-redis
        ports:
            - 9000:9000

    laravelapi-postgres:
        image: postgres:12-alpine
        restart: always
        ports:
            - 5432:5432
        volumes:
            - "./.docker/postgres/data:/var/lib/postgresql/data"
        environment:
            - POSTGRES_DB=laravel
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    laravelapi-redis:
        image: redis:alpine
        user: ${DOCKER_UID}
        volumes:
            - ./.docker/redis:/data
        ports:
            - 6379:6379

    laravelapi-nginx:
        build: ./.docker/nginx
        restart: always
        ports:
            - "${DOCKER_PORT}:80"
        volumes:
            - laravelapi-app-sync:/var/www
            - laravelapi-vendor-sync:/var/www/vendor
            - ./.docker/log/nginx:/var/log/nginx
        depends_on:
            - laravelapi

volumes:
  laravelapi-vendor-sync:
    external: true
  laravelapi-app-sync:
    external: true
